### PR TITLE
Update .travis.yaml, hopefully this works

### PR DESCRIPTION
**Pull request by sid-kap**
It was complaining that I was trying to run `./generate-stack-yaml` before installing a system-wide GHC: https://travis-ci.org/diagrams/diagrams-doc/builds/132947544

### CODE REVIEW

**Comment by byorgey** [comment]
Hmm, looks like OOM error this time?

**Comment by sid-kap** [comment]
Okay, trying again with 1 thread. This will be very slow, but hopefully we only have to do it once because the results should be cached.

**Comment by sid-kap** [comment]
If we merge this, I don't know if Travis will copy over the cache from this branch over to master. If not, we might get the same OOM on master. What do you think we should do? 

One option would be to do this in two stages: First, commit to master with `-j 1`, so that Stack builds everything single-threaded. Then, make another commit that removes the `-j 1`. At this point, the cache will contain most of the built packages, so there would be little risk of OOMs.

The other option would be to just merge this and hope for the best. If there are errors, we could then try something like the first option above.

**Comment by byorgey** [comment]
Yeah, let's just merge it and see what happens.  We'll learn something about Travis that way as well. =)

**Pull request merged**
