### PR TITLE
Added Heighway dragons to gallery

### PR DESCRIPTION
**Pull request by pnutus**
I've attached a picture of the diagram below.

I'm unsure if I should submit a separate gallery entry for just one dragon. This example is as much layout as it is fractal; perhaps having both in the gallery is desirable? Also, I don't think the thumbnail will work that well; it will be hard to see that it is a fractal.
there be dragons

### CODE REVIEW

**Comment by byorgey** [comment]
Thanks, I think this makes for a fantastic gallery entry!  As for the thumbnail, you can define an attribute `view` which specifies which portion of the image should be selected, if you want to override the default.  You can see an example here: https://github.com/diagrams/diagrams-doc/blob/master/web/gallery/Quasifuchsian.lhs .

**Comment by byorgey** [comment]
I'll go ahead and merge this, and you should feel free to fiddle with the `view` if you like.

**Comment by pnutus** [comment]
Glad you liked it!

I have put some effort into it, but I don't think I have the patience to get `diagrams-doc` building. Is there a way for me to preview the `view` configuration of just my file without spending a lot of time figuring out how `diagrams-builder` et al. does their magic?

**Comment by byorgey** [comment]
No, there's no easy way that I know of.  Don't worry about.  I or someone else will be happy to twiddle `view` next time we get around to building `diagrams-doc`.  In related news, I am currently working on some tooling using `stack` which should make it much easier to build `diagrams-doc`.

**Comment by pnutus** [comment]
Cool! I tried building `diagrams-doc` with stack, but found `docutils` a pain to deal with. I would be happy to help improve the docs, so I think facilitating contributions is great!

**Comment by byorgey** [comment]
Yep, not coincidentally, I have just been working on updating docutils to
work with GHC 7.10.

**Pull request merged**
